name: Deploy Quartz site to GitHub Pages

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 05:00 UTC
  workflow_dispatch:       # Manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # So we can compare to the previous commit

      - name: Check for relevant file changes
        id: changes
        run: |
          echo "Checking for changes in content/, quartz/, or config files..."
          if git diff --quiet HEAD^ HEAD -- content/ quartz/ quartz.config.ts package.json; then
            echo "No relevant changes detected."
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if nothing changed
        if: steps.changes.outputs.should_skip == 'true'
        run: echo "Skipping build – no changes detected." && exit 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
